version: '3.8'
 
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-dock-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
 
  spring-app:
    build: .
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
 
